### ISSUE TITLE
Tests in error

### ISSUE THREAD

**Issue by EGobi** [OpticFusion1/Multiverse-Core#2]
Six tests are returning error when building with `mvn install`: `TestDebugMode`, `TestEntitySpawnRules`, `TestModifyCommand`, `TestWorldProperties`, `TestWorldPurger `and `TestWorldStuff`. The following report applies to them:
```
-------------------------------------------------------------------------------
Test set: com.onarandombox.MultiverseCore.TestXXXXX
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.003 sec <<< FAILURE! - in com.onarandombox.MultiverseCore.TestXXXXX
initializationError(com.onarandombox.MultiverseCore.TestXXXXX)  Time elapsed: 0.003 sec  <<< ERROR!
org.objenesis.ObjenesisException: java.lang.reflect.InvocationTargetException
Caused by: java.lang.reflect.InvocationTargetException
Caused by: java.lang.IllegalAccessError: class jdk.internal.reflect.ConstructorAccessorImpl loaded by org.powermock.core.classloader.MockClassLoader @YYYYY cannot access jdk/internal/reflect superclass jdk.internal.reflect.MagicAccessorImpl
```
Where XXXXX stands for each test and YYYYY is, respectively, `3b2c72c2`, `2ddc8ecb`, `45b9a632`, `d4342c2`, `6193932a` and `7ee955a8`.

**Comment by OpticFusion1** [comment]
try it again? I recompiled the plugin and didn't run into this sort of issue, also try compiling it from an IDE

**Comment by EGobi** [comment]
>try it again? I recompiled the plugin and didn't run into this sort of issue, also try compiling it from an IDE

Tried to compile with NetBeans, same errors appeared. Then I tried on command line with `mvn install -DskipTests=true`, and surprisingly it actually worked (tested on my CraftBukkit server and it ran ok).

**Comment by OpticFusion1** [comment]
> 
> 
> > try it again? I recompiled the plugin and didn't run into this sort of issue, also try compiling it from an IDE
> 
> Tried to compile with NetBeans, same errors appeared. Then I tried on command line with `mvn install -DskipTests=true`, and surprisingly it actually worked (tested on my CraftBukkit server and it ran ok).

Strange o.O i'm not sure why it's erroring if you're not using -DskipTests=true, i'll have to look into it if i run into the error because i'm not reproducing it..
